# Generated by Django 3.2.7 on 2022-04-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rating_ratingstar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingstar',
            name='id',
        ),
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.SmallIntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
