# Generated by Django 3.2.7 on 2022-04-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_infouser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumbition',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sumbitions', to='main.survey', verbose_name='Survey'),
        ),
    ]
