# Generated by Django 3.2.7 on 2022-04-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_sumbition_survey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Info user', 'verbose_name_plural': 'Info users'},
        ),
    ]
